# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QHBoxLayout, QLabel, QLayout, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QSpinBox, QStatusBar, QTimeEdit, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(545, 645)
        icon = QIcon()
        icon.addFile(u"F:/PythonProject/Pomodoro_BSOD/icon/logo.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"font: 700 14pt \"Microsoft YaHei UI\";")
        self.light_white = QAction(MainWindow)
        self.light_white.setObjectName(u"light_white")
        self.dark_black = QAction(MainWindow)
        self.dark_black.setObjectName(u"dark_black")
        self.chinese = QAction(MainWindow)
        self.chinese.setObjectName(u"chinese")
        self.english = QAction(MainWindow)
        self.english.setObjectName(u"english")
        self.pomodoro = QAction(MainWindow)
        self.pomodoro.setObjectName(u"pomodoro")
        self.info = QAction(MainWindow)
        self.info.setObjectName(u"info")
        self.update = QAction(MainWindow)
        self.update.setObjectName(u"update")
        self.tray = QAction(MainWindow)
        self.tray.setObjectName(u"tray")
        self.minimize = QAction(MainWindow)
        self.minimize.setObjectName(u"minimize")
        self.exit = QAction(MainWindow)
        self.exit.setObjectName(u"exit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.label_title = QLabel(self.centralwidget)
        self.label_title.setObjectName(u"label_title")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setFamilies([u"Microsoft YaHei UI"])
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet(u"font: 700 24pt \"Microsoft YaHei UI\";")
        self.label_title.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_title)

        self.formLayout_1 = QFormLayout()
        self.formLayout_1.setObjectName(u"formLayout_1")
        self.formLayout_1.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        self.formLayout_1.setRowWrapPolicy(QFormLayout.RowWrapPolicy.DontWrapRows)
        self.formLayout_1.setHorizontalSpacing(30)
        self.formLayout_1.setVerticalSpacing(30)
        self.formLayout_1.setContentsMargins(-1, 10, -1, 10)
        self.label_pomodoro = QLabel(self.centralwidget)
        self.label_pomodoro.setObjectName(u"label_pomodoro")
        font1 = QFont()
        font1.setFamilies([u"Microsoft YaHei UI"])
        font1.setPointSize(14)
        font1.setBold(False)
        font1.setItalic(False)
        self.label_pomodoro.setFont(font1)
        self.label_pomodoro.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label_pomodoro)

        self.comboBox_pomodoro = QComboBox(self.centralwidget)
        self.comboBox_pomodoro.addItem("")
        self.comboBox_pomodoro.addItem("")
        self.comboBox_pomodoro.addItem("")
        self.comboBox_pomodoro.setObjectName(u"comboBox_pomodoro")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.comboBox_pomodoro.sizePolicy().hasHeightForWidth())
        self.comboBox_pomodoro.setSizePolicy(sizePolicy2)
        self.comboBox_pomodoro.setMinimumSize(QSize(0, 30))
        self.comboBox_pomodoro.setFont(font1)
        self.comboBox_pomodoro.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.comboBox_pomodoro.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(0, QFormLayout.ItemRole.FieldRole, self.comboBox_pomodoro)

        self.label_screensaver = QLabel(self.centralwidget)
        self.label_screensaver.setObjectName(u"label_screensaver")
        self.label_screensaver.setFont(font1)
        self.label_screensaver.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(1, QFormLayout.ItemRole.LabelRole, self.label_screensaver)

        self.comboBox_screensaver = QComboBox(self.centralwidget)
        self.comboBox_screensaver.addItem("")
        self.comboBox_screensaver.addItem("")
        self.comboBox_screensaver.addItem("")
        self.comboBox_screensaver.setObjectName(u"comboBox_screensaver")
        sizePolicy2.setHeightForWidth(self.comboBox_screensaver.sizePolicy().hasHeightForWidth())
        self.comboBox_screensaver.setSizePolicy(sizePolicy2)
        self.comboBox_screensaver.setMinimumSize(QSize(0, 30))
        self.comboBox_screensaver.setFont(font1)
        self.comboBox_screensaver.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.comboBox_screensaver.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(1, QFormLayout.ItemRole.FieldRole, self.comboBox_screensaver)

        self.label_hardMode = QLabel(self.centralwidget)
        self.label_hardMode.setObjectName(u"label_hardMode")
        self.label_hardMode.setFont(font1)
        self.label_hardMode.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(2, QFormLayout.ItemRole.LabelRole, self.label_hardMode)

        self.checkBox_hardMode = QCheckBox(self.centralwidget)
        self.checkBox_hardMode.setObjectName(u"checkBox_hardMode")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.checkBox_hardMode.sizePolicy().hasHeightForWidth())
        self.checkBox_hardMode.setSizePolicy(sizePolicy3)
        self.checkBox_hardMode.setMinimumSize(QSize(0, 30))
        self.checkBox_hardMode.setFont(font1)
        self.checkBox_hardMode.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.checkBox_hardMode.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(2, QFormLayout.ItemRole.FieldRole, self.checkBox_hardMode)

        self.label_workTime = QLabel(self.centralwidget)
        self.label_workTime.setObjectName(u"label_workTime")
        self.label_workTime.setFont(font1)
        self.label_workTime.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(3, QFormLayout.ItemRole.LabelRole, self.label_workTime)

        self.label_shortRestTime = QLabel(self.centralwidget)
        self.label_shortRestTime.setObjectName(u"label_shortRestTime")
        self.label_shortRestTime.setFont(font1)
        self.label_shortRestTime.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(4, QFormLayout.ItemRole.LabelRole, self.label_shortRestTime)

        self.label_longRestTime = QLabel(self.centralwidget)
        self.label_longRestTime.setObjectName(u"label_longRestTime")
        self.label_longRestTime.setFont(font1)
        self.label_longRestTime.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(5, QFormLayout.ItemRole.LabelRole, self.label_longRestTime)

        self.label_concentration = QLabel(self.centralwidget)
        self.label_concentration.setObjectName(u"label_concentration")
        self.label_concentration.setFont(font1)
        self.label_concentration.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(6, QFormLayout.ItemRole.LabelRole, self.label_concentration)

        self.label_loopCount = QLabel(self.centralwidget)
        self.label_loopCount.setObjectName(u"label_loopCount")
        self.label_loopCount.setFont(font1)
        self.label_loopCount.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(7, QFormLayout.ItemRole.LabelRole, self.label_loopCount)

        self.timeEdit_workTime = QTimeEdit(self.centralwidget)
        self.timeEdit_workTime.setObjectName(u"timeEdit_workTime")
        sizePolicy3.setHeightForWidth(self.timeEdit_workTime.sizePolicy().hasHeightForWidth())
        self.timeEdit_workTime.setSizePolicy(sizePolicy3)
        self.timeEdit_workTime.setMinimumSize(QSize(0, 30))
        self.timeEdit_workTime.setFont(font1)
        self.timeEdit_workTime.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.timeEdit_workTime.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(3, QFormLayout.ItemRole.FieldRole, self.timeEdit_workTime)

        self.timeEdit_shortRestTime = QTimeEdit(self.centralwidget)
        self.timeEdit_shortRestTime.setObjectName(u"timeEdit_shortRestTime")
        sizePolicy3.setHeightForWidth(self.timeEdit_shortRestTime.sizePolicy().hasHeightForWidth())
        self.timeEdit_shortRestTime.setSizePolicy(sizePolicy3)
        self.timeEdit_shortRestTime.setMinimumSize(QSize(0, 30))
        self.timeEdit_shortRestTime.setFont(font1)
        self.timeEdit_shortRestTime.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.timeEdit_shortRestTime.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(4, QFormLayout.ItemRole.FieldRole, self.timeEdit_shortRestTime)

        self.timeEdit_longRestTime = QTimeEdit(self.centralwidget)
        self.timeEdit_longRestTime.setObjectName(u"timeEdit_longRestTime")
        sizePolicy3.setHeightForWidth(self.timeEdit_longRestTime.sizePolicy().hasHeightForWidth())
        self.timeEdit_longRestTime.setSizePolicy(sizePolicy3)
        self.timeEdit_longRestTime.setMinimumSize(QSize(0, 30))
        self.timeEdit_longRestTime.setFont(font1)
        self.timeEdit_longRestTime.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.timeEdit_longRestTime.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.formLayout_1.setWidget(5, QFormLayout.ItemRole.FieldRole, self.timeEdit_longRestTime)

        self.spinBox_concentration = QSpinBox(self.centralwidget)
        self.spinBox_concentration.setObjectName(u"spinBox_concentration")
        sizePolicy3.setHeightForWidth(self.spinBox_concentration.sizePolicy().hasHeightForWidth())
        self.spinBox_concentration.setSizePolicy(sizePolicy3)
        self.spinBox_concentration.setMinimumSize(QSize(0, 30))
        self.spinBox_concentration.setFont(font1)
        self.spinBox_concentration.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.spinBox_concentration.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")
        self.spinBox_concentration.setMinimum(1)

        self.formLayout_1.setWidget(6, QFormLayout.ItemRole.FieldRole, self.spinBox_concentration)

        self.spinBox_loopCount = QSpinBox(self.centralwidget)
        self.spinBox_loopCount.setObjectName(u"spinBox_loopCount")
        sizePolicy3.setHeightForWidth(self.spinBox_loopCount.sizePolicy().hasHeightForWidth())
        self.spinBox_loopCount.setSizePolicy(sizePolicy3)
        self.spinBox_loopCount.setMinimumSize(QSize(0, 30))
        self.spinBox_loopCount.setFont(font1)
        self.spinBox_loopCount.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.spinBox_loopCount.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")
        self.spinBox_loopCount.setMinimum(1)

        self.formLayout_1.setWidget(7, QFormLayout.ItemRole.FieldRole, self.spinBox_loopCount)


        self.verticalLayout_3.addLayout(self.formLayout_1)

        self.horizontalLayout_1 = QHBoxLayout()
        self.horizontalLayout_1.setSpacing(10)
        self.horizontalLayout_1.setObjectName(u"horizontalLayout_1")
        self.pushButton_start = QPushButton(self.centralwidget)
        self.pushButton_start.setObjectName(u"pushButton_start")
        sizePolicy3.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy3)
        self.pushButton_start.setMinimumSize(QSize(0, 40))
        self.pushButton_start.setFont(font1)
        self.pushButton_start.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.pushButton_start.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.horizontalLayout_1.addWidget(self.pushButton_start)

        self.pushButton_stop = QPushButton(self.centralwidget)
        self.pushButton_stop.setObjectName(u"pushButton_stop")
        sizePolicy3.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy3)
        self.pushButton_stop.setMinimumSize(QSize(0, 40))
        self.pushButton_stop.setFont(font1)
        self.pushButton_stop.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.pushButton_stop.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.horizontalLayout_1.addWidget(self.pushButton_stop)

        self.pushButton_pause = QPushButton(self.centralwidget)
        self.pushButton_pause.setObjectName(u"pushButton_pause")
        self.pushButton_pause.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.pushButton_pause.sizePolicy().hasHeightForWidth())
        self.pushButton_pause.setSizePolicy(sizePolicy3)
        self.pushButton_pause.setMinimumSize(QSize(0, 40))
        self.pushButton_pause.setFont(font1)
        self.pushButton_pause.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.pushButton_pause.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")

        self.horizontalLayout_1.addWidget(self.pushButton_pause)


        self.verticalLayout_3.addLayout(self.horizontalLayout_1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"font: 12pt \"Microsoft YaHei UI\";")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 545, 33))
        self.menubar.setFont(font1)
        self.menubar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.menubar.setStyleSheet(u"font: 14pt \"Microsoft YaHei UI\";")
        self.menu_theme = QMenu(self.menubar)
        self.menu_theme.setObjectName(u"menu_theme")
        self.menu_theme.setFont(font1)
        self.menu_language = QMenu(self.menubar)
        self.menu_language.setObjectName(u"menu_language")
        self.menu_language.setFont(font1)
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_help.setFont(font1)
        self.menu_about = QMenu(self.menubar)
        self.menu_about.setObjectName(u"menu_about")
        self.menu_about.setFont(font1)
        self.menu_window = QMenu(self.menubar)
        self.menu_window.setObjectName(u"menu_window")
        self.menu_window.setFont(font1)
        MainWindow.setMenuBar(self.menubar)
#if QT_CONFIG(shortcut)
        self.label_pomodoro.setBuddy(self.comboBox_pomodoro)
        self.label_screensaver.setBuddy(self.comboBox_pomodoro)
        self.label_workTime.setBuddy(self.timeEdit_workTime)
        self.label_shortRestTime.setBuddy(self.timeEdit_shortRestTime)
        self.label_longRestTime.setBuddy(self.timeEdit_longRestTime)
        self.label_concentration.setBuddy(self.spinBox_concentration)
        self.label_loopCount.setBuddy(self.spinBox_loopCount)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.comboBox_pomodoro, self.comboBox_screensaver)
        QWidget.setTabOrder(self.comboBox_screensaver, self.timeEdit_workTime)
        QWidget.setTabOrder(self.timeEdit_workTime, self.timeEdit_shortRestTime)
        QWidget.setTabOrder(self.timeEdit_shortRestTime, self.timeEdit_longRestTime)
        QWidget.setTabOrder(self.timeEdit_longRestTime, self.spinBox_concentration)
        QWidget.setTabOrder(self.spinBox_concentration, self.spinBox_loopCount)
        QWidget.setTabOrder(self.spinBox_loopCount, self.pushButton_start)
        QWidget.setTabOrder(self.pushButton_start, self.pushButton_stop)
        QWidget.setTabOrder(self.pushButton_stop, self.pushButton_pause)

        self.menubar.addAction(self.menu_theme.menuAction())
        self.menubar.addAction(self.menu_language.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menubar.addAction(self.menu_about.menuAction())
        self.menubar.addAction(self.menu_window.menuAction())
        self.menu_theme.addAction(self.light_white)
        self.menu_theme.addAction(self.dark_black)
        self.menu_language.addAction(self.chinese)
        self.menu_language.addAction(self.english)
        self.menu_help.addAction(self.pomodoro)
        self.menu_about.addAction(self.info)
        self.menu_about.addAction(self.update)
        self.menu_window.addAction(self.tray)
        self.menu_window.addAction(self.minimize)
        self.menu_window.addAction(self.exit)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u84dd\u5c4f\u756a\u8304\u949f", None))
        self.light_white.setText(QCoreApplication.translate("MainWindow", u"\u4eae\u8272", None))
        self.dark_black.setText(QCoreApplication.translate("MainWindow", u"\u6697\u8272", None))
        self.chinese.setText(QCoreApplication.translate("MainWindow", u"\u7b80\u4f53\u4e2d\u6587", None))
        self.english.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.pomodoro.setText(QCoreApplication.translate("MainWindow", u"\u756a\u8304\u949f\u4ecb\u7ecd", None))
        self.info.setText(QCoreApplication.translate("MainWindow", u"\u8f6f\u4ef6\u8bf4\u660e", None))
        self.update.setText(QCoreApplication.translate("MainWindow", u"\u8f6f\u4ef6\u66f4\u65b0", None))
        self.tray.setText(QCoreApplication.translate("MainWindow", u"\u6258\u76d8\u5316", None))
        self.minimize.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0f\u5316", None))
        self.exit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.label_title.setText(QCoreApplication.translate("MainWindow", u"\u84dd\u5c4f\u756a\u8304\u949f", None))
        self.label_pomodoro.setText(QCoreApplication.translate("MainWindow", u"\u65f6\u949f\u9884\u8bbe\uff1a", None))
        self.comboBox_pomodoro.setItemText(0, QCoreApplication.translate("MainWindow", u"\u6807\u51c6\u756a\u8304\u949f", None))
        self.comboBox_pomodoro.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6574\u86ca\u6a21\u5f0f", None))
        self.comboBox_pomodoro.setItemText(2, QCoreApplication.translate("MainWindow", u"\u81ea\u5b9a\u4e49...", None))

#if QT_CONFIG(tooltip)
        self.comboBox_pomodoro.setToolTip(QCoreApplication.translate("MainWindow", u"\u66f4\u6539\u9884\u8bbe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.comboBox_pomodoro.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.comboBox_pomodoro.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.label_screensaver.setText(QCoreApplication.translate("MainWindow", u"\u4f11\u606f\u5c4f\u4fdd\uff1a", None))
        self.comboBox_screensaver.setItemText(0, QCoreApplication.translate("MainWindow", u"\u84dd\u5c4f\u6b7b\u673a", None))
        self.comboBox_screensaver.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5f69\u8679\u732b", None))
        self.comboBox_screensaver.setItemText(2, QCoreApplication.translate("MainWindow", u"\u6b63\u5e38\u63d0\u9192", None))

#if QT_CONFIG(tooltip)
        self.comboBox_screensaver.setToolTip(QCoreApplication.translate("MainWindow", u"\u66f4\u6539\u4f11\u606f\u65f6\u663e\u793a\u7684\u5c4f\u4fdd", None))
#endif // QT_CONFIG(tooltip)
        self.label_hardMode.setText(QCoreApplication.translate("MainWindow", u"\u786c\u6838\u6a21\u5f0f\uff1a", None))
#if QT_CONFIG(tooltip)
        self.checkBox_hardMode.setToolTip(QCoreApplication.translate("MainWindow", u"\u614e\u7528\u786c\u6838\u6a21\u5f0f", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox_hardMode.setText(QCoreApplication.translate("MainWindow", u"\u7981\u7528\u952e\u76d8\u548c\u9f20\u6807\uff0c\u4f11\u606f\u671f\u95f4\u65e0\u6cd5\u6b63\u5e38\u9000\u51fa", None))
        self.label_workTime.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u4f5c\u65f6\u95f4\uff1a", None))
        self.label_shortRestTime.setText(QCoreApplication.translate("MainWindow", u"\u77ed\u4f11\u65f6\u95f4\uff1a", None))
        self.label_longRestTime.setText(QCoreApplication.translate("MainWindow", u"\u957f\u4f11\u65f6\u95f4\uff1a", None))
        self.label_concentration.setText(QCoreApplication.translate("MainWindow", u"\u4e13\u6ce8\u8f6e\u6570\uff1a", None))
        self.label_loopCount.setText(QCoreApplication.translate("MainWindow", u"\u756a\u8304\u4e2a\u6570\uff1a", None))
#if QT_CONFIG(tooltip)
        self.timeEdit_workTime.setToolTip(QCoreApplication.translate("MainWindow", u"\u5de5\u4f5c\u7684\u65f6\u95f4", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.timeEdit_shortRestTime.setToolTip(QCoreApplication.translate("MainWindow", u"\u77ed\u4f11\u606f\u7684\u65f6\u95f4", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.timeEdit_longRestTime.setToolTip(QCoreApplication.translate("MainWindow", u"\u957f\u4f11\u606f\u7684\u65f6\u95f4", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.spinBox_concentration.setToolTip(QCoreApplication.translate("MainWindow", u"\u8fdb\u884c\u51e0\u8f6e\u4e13\u6ce8", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.spinBox_loopCount.setToolTip(QCoreApplication.translate("MainWindow", u"\u756a\u8304\u949f\u5faa\u73af\u51e0\u6b21", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pushButton_start.setToolTip(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u756a\u8304\u949f", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_start.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
#if QT_CONFIG(tooltip)
        self.pushButton_stop.setToolTip(QCoreApplication.translate("MainWindow", u"\u505c\u6b62\u756a\u8304\u949f", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_stop.setText(QCoreApplication.translate("MainWindow", u"\u505c\u6b62", None))
#if QT_CONFIG(tooltip)
        self.pushButton_pause.setToolTip(QCoreApplication.translate("MainWindow", u"\u6682\u505c\u756a\u8304\u949f", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_pause.setText(QCoreApplication.translate("MainWindow", u"\u6682\u505c", None))
        self.menu_theme.setTitle(QCoreApplication.translate("MainWindow", u"\u4e3b\u9898", None))
        self.menu_language.setTitle(QCoreApplication.translate("MainWindow", u"\u8bed\u8a00", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.menu_about.setTitle(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.menu_window.setTitle(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3", None))
    # retranslateUi

